import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Main from '../components/Main'
import Instructions from '../components/Instructions'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shopify Intern Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/shopifyweb.svg" />
      </Head>
      <header className={styles.header}>
        <h1>Welcome to the AI Genie Response App</h1>
      </header>
      <main className={styles.main}>
        <Instructions />
        <Main />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{''}
          <span className={styles.logo}>
            <Image src="/shopify.svg" alt="Shopify Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
